Redirect BiomeLayers.getModdedBiomeSize to PatchworkBiomeLayers
PatchworkMC/patchwork-patcher pull request #60
Opened 2020-07-08 14:08 UTC by leo60228

2020-07-08 15:04 UTC, coderbot16 requested changes
Looks good to me, but it looks like you removed the wrong NEW redirect.

2020-07-08 15:04 UTC, coderbot16 commented on src/main/java/com/patchworkmc/patch/LevelGeneratorTypeTransformer.java
> -		public void visitTypeInsn(int opcode, String type) {
Why is this removed? As far as I can tell, it's needed for level generator types to properly work.

2020-07-08 15:04 UTC, coderbot16 commented on src/main/java/com/patchworkmc/patch/BiomeLayersTransformer.java
> +		public void visitTypeInsn(int opcode, String type) {
I don't think that anyone will be needing to initialize BiomeLayers? Or at least, it won't need to be redirected.

2020-07-08 15:04 UTC, leo60228 commented
Oops... I'll fix that after I eat breakfast.

2020-07-08 15:05 UTC, coderbot16 commented
Sounds good!

2020-07-08 17:19 UTC, coderbot16 commented on src/main/java/com/patchworkmc/patch/BiomeLayersTransformer.java
> +		super.visit(version, access, name, signature, BIOME_LAYERS_NAME.equals(superName) ? PATCHWORK_BIOME_LAYERS_NAME : superName, interfaces);
This probably isn't needed either

2020-07-08 17:19 UTC, coderbot16 requested changes
Looks mostly good, just noticed one other small issue.

2020-07-09 02:15 UTC, coderbot16 approved these changes
Looks good to me!

2020-07-09 02:15 UTC, merged